# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: myportfolio/conf.py  # conf.py ထားပြီး path ကို စစ်ပြင်လိုက်ပါ။

python:
  install:
    - requirements: myportfolio/requirements.txt  # မလိုအပ်မယ်ဆို comment ထားနိုင်ပါတယ်။
